### ISSUE TITLE
I'm new to bots

### ISSUE THREAD

**Issue by johndpope** [aleksspevak/lorabot#1]
**Initialize LoraBot in your bot:**

can you unpack this line? I don't have a bot.

UPDATE
go here -> https://t.me/botfather

/newBot

get the token 

now what....

**Comment by alekskram** [comment]
Hi!
So, if you wrote about paragraph 5 of [this](https://github.com/aleksspevak/lorabot#how-add-analytics-to-your-project), then you need to understand that this paragraph is about initializing analytics in your (in this case Telegram) bot, and not about how to initialize a bot in a Telegram and get a token.
That is, the initialization of analytics in the bot code.

I'm strongly recommend to read more about how to create telegram bots. I'm prefer to use for example [pyTelegramBotAPI](https://github.com/eternnoir/pyTelegramBotAPI) library. To learn more about it you should read [this](https://betterprogramming.pub/how-to-create-telegram-bot-in-python-cccc4babcc30) or [this.](https://medium.com/analytics-vidhya/build-and-deploy-your-first-telegram-bot-using-python-part-1-dcfd83bd6718)
And if you use this library you should put your token for using Telegram API like here:
```
import telebot
bot = telebot.TeleBot("TOKEN_FROM_BOTFATHER")
```

Back to your question, to initialize LoraBot you should add this:
```
import telebot
from lorabot import LoraBot
bot = telebot.TeleBot("TOKEN_FROM_BOTFATHER")
lora_bot = LoraBot("your bot's name")
```
So core thing is that LoraBot is not a wrapper for Telegram API to create bots.
LoraBot is tool to add analytics in chat bots.

**Comment by johndpope** [comment]
thanks so much Aleks.
